### ISSUE TITLE
[Tutorial 2 + 3] Error when loading test_build.fatbin file in tutorials (No kernel image is available for execution on the device)

### ISSUE THREAD

**Issue by rllyryan** [salesforce/warp-drive#37]
Dear WarpDrive team,

I have came across an error that is consistent in tutorials 2 and 3.

The error occurs when this particular line of code is run-ed:
```
cuda_function_manager.load_cuda_from_binary_file(f"{_CUBIN_FILEPATH}/test_build.fatbin")
```
and the error that pops-up is:
```
RuntimeError: cuModuleLoad failed: no kernel image is available for execution on the device
```
Is there a solution or a work around for this?

I am trying to learning WarpDrive to implement it for a MARL path finding scenario for possible use in application scenarios (i.e., warehouses).

Thank you and I appreciate your prompt reply in this :)

**Comment by Emerald01** [comment]
Dear @rllyryan 
Thank you for pointing out this issue. This is not a bug but only on Colab. It seems that Colab has certain framework update and incurs incompatibility (which was running well before) with our pre-compiled test_build.fatbin that we built in our local CUDA environment long time ago. Therefore, we now explicitly ask WarpDrive to re-compile the demo binary on-the-fly at Colab directly, and it seems fix both Tutorial 2 and 3. Please let me know if you are still facing any issue.

Tutorial 2 + 3 show some low-level APIs like sampler and resetter and how we compile, call and test them. Keep in mind that in our end-to-end simulation and trainer, they are hidden and managed automatically, and will not be called directly by the user, so do not get scared if you feel the initialization takes a few lines of codes :)

**Comment by rllyryan** [comment]
> Dear @rllyryan Thank you for pointing out this issue. This is not a bug but only on Colab. It seems that Colab has certain framework update and incurs incompatibility (which was running well before) with our pre-compiled test_build.fatbin that we built in our local CUDA environment long time ago. Therefore, we now explicitly ask WarpDrive to re-compile the demo binary on-the-fly at Colab directly, and it seems fix both Tutorial 2 and 3. In particular, you can see that we call a low-level API: _compile() to fulfil this. Please let me know if you are still facing any issue.
> 
> Tutorial 2 + 3 show some low-level APIs like sampler and resetter and how we compile, call and test them. Keep in mind that in our end-to-end simulation and trainer, they are hidden and managed automatically, and will not be called directly by the user, so do not get scared if you feel the initialization takes a few extra lines of codes :)

Thank you @Emerald01 for sorting this out! The two tutorials work just fine now :)

From this, I can figure that the dynamic environment of Google Colab might cause some issues with my implementation of WarpDrive if I were to utilise Google Colab. 

Can I ask for you recommendation as to how should I host WarpDrive on my local machine? Should I pip install it on the local machine or repeatedly pip installing it on a remote server like Colab and Jupyter? This is to prevent any sudden incompatibilities that may arise.

Thank you!
