### ISSUE TITLE
problem with running environment

### ISSUE THREAD

**Issue by DanielWit** [salesforce/warp-drive#48]
Hi, 

Need some help to make this run. The issue is happening in Jupyter and in PyCharm, 'make bin file failed..' exception is raised over and over again. The exception is raised in simple-end-to-end example and also while running both tests build in the library.
Fresh Conda environment.

Thanks for any suggestions 

appdirs                   1.4.4                    pypi_0    pypi
atomicwrites              1.4.0                      py_0
attrs                     21.4.0             pyhd3eb1b0_0
backcall                  0.2.0                    pypi_0    pypi
blas                      1.0                         mkl
brotli                    1.0.9                h2bbff1b_7
brotli-bin                1.0.9                h2bbff1b_7
ca-certificates           2022.07.19           haa95532_0
certifi                   2022.6.15        py37haa95532_0
charset-normalizer        2.1.1                    pypi_0    pypi
cloudpickle               2.1.0                    pypi_0    pypi
colorama                  0.4.5            py37haa95532_0
cycler                    0.11.0             pyhd3eb1b0_0
debugpy                   1.6.3                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
fonttools                 4.25.0             pyhd3eb1b0_0
freetype                  2.10.4               hd328e21_0
glib                      2.69.1               h5dc1a3c_1
gst-plugins-base          1.18.5               h9e645db_0
gstreamer                 1.18.5               hd78058f_0
gym                       0.25.2                   pypi_0    pypi
gym-notices               0.0.8                    pypi_0    pypi
icu                       58.2                 ha925a31_3
idna                      3.3                      pypi_0    pypi
importlib-metadata        4.11.3           py37haa95532_0
importlib_metadata        4.11.3               hd3eb1b0_0
iniconfig                 1.1.1              pyhd3eb1b0_0
intel-openmp              2021.4.0          haa95532_3556
ipykernel                 6.15.1                   pypi_0    pypi
ipython                   7.34.0                   pypi_0    pypi
jedi                      0.18.1                   pypi_0    pypi
jpeg                      9e                   h2bbff1b_0
jupyter-client            7.3.4                    pypi_0    pypi
jupyter-core              4.11.1                   pypi_0    pypi
kiwisolver                1.4.2            py37hd77b12b_0
lerc                      3.0                  hd77b12b_0
libbrotlicommon           1.0.9                h2bbff1b_7
libbrotlidec              1.0.9                h2bbff1b_7
libbrotlienc              1.0.9                h2bbff1b_7
libclang                  12.0.0          default_h627e005_2
libdeflate                1.8                  h2bbff1b_5
libffi                    3.4.2                hd77b12b_4
libiconv                  1.16                 h2bbff1b_2
libogg                    1.3.5                h2bbff1b_1
libpng                    1.6.37               h2a8f88b_0
libtiff                   4.4.0                h8a3f274_0
libvorbis                 1.3.7                he774522_0
libwebp                   1.2.2                h2bbff1b_0
libxml2                   2.9.14               h0ad7f3c_0
libxslt                   1.1.35               h2bbff1b_0
lz4-c                     1.9.3                h2bbff1b_1
mako                      1.2.1                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                3.5.1            py37haa95532_1
matplotlib-base           3.5.1            py37hd77b12b_1
matplotlib-inline         0.1.6                    pypi_0    pypi
mkl                       2021.4.0           haa95532_640
mkl-service               2.4.0            py37h2bbff1b_0
mkl_fft                   1.3.1            py37h277e83a_0
mkl_random                1.2.2            py37hf11a4ad_0
munkres                   1.1.4                      py_0
nest-asyncio              1.5.5                    pypi_0    pypi
numpy                     1.21.5           py37h7a0a035_3
numpy-base                1.21.5           py37hca35cd5_3
openssl                   1.1.1q               h2bbff1b_0
packaging                 21.3               pyhd3eb1b0_0
parso                     0.8.3                    pypi_0    pypi
pcre                      8.45                 hd77b12b_0
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.2.0            py37hdc2b20a_1
pip                       22.1.2           py37haa95532_0
platformdirs              2.5.2                    pypi_0    pypi
pluggy                    1.0.0            py37haa95532_1
ply                       3.11                     py37_0
prompt-toolkit            3.0.30                   pypi_0    pypi
psutil                    5.9.1                    pypi_0    pypi
py                        1.11.0             pyhd3eb1b0_0
pycuda                    2021.1                   pypi_0    pypi
pygments                  2.13.0                   pypi_0    pypi
pyparsing                 3.0.4              pyhd3eb1b0_0
pyqt                      5.15.7           py37hd77b12b_0
pyqt5-sip                 12.11.0          py37hd77b12b_0
pytest                    7.1.2            py37haa95532_0
python                    3.7.13               h6244533_0
python-dateutil           2.8.2              pyhd3eb1b0_0
pytools                   2022.1.12                pypi_0    pypi
pywin32                   304                      pypi_0    pypi
pyyaml                    6.0              py37h2bbff1b_1
pyzmq                     23.2.1                   pypi_0    pypi
qt-main                   5.15.2               he8e5bd7_7
qt-webengine              5.15.9               hb9a9bb5_4
qtwebkit                  5.212                h3ad3cdb_4
requests                  2.28.1                   pypi_0    pypi
rl-warp-drive             1.6.7                    pypi_0    pypi
setuptools                61.2.0           py37haa95532_0
sip                       6.6.2            py37hd77b12b_0
six                       1.16.0             pyhd3eb1b0_1
sqlite                    3.39.2               h2bbff1b_0
tk                        8.6.12               h2bbff1b_0
toml                      0.10.2             pyhd3eb1b0_0
tomli                     2.0.1            py37haa95532_0
torch                     1.10.2                   pypi_0    pypi
torchaudio                0.12.1+cu116             pypi_0    pypi
torchtext                 0.11.2                   pypi_0    pypi
torchvision               0.11.3                   pypi_0    pypi
tornado                   6.1              py37h2bbff1b_0
tqdm                      4.64.0                   pypi_0    pypi
traitlets                 5.3.0                    pypi_0    pypi
typing_extensions         4.3.0            py37haa95532_0
urllib3                   1.26.11                  pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wcwidth                   0.2.5                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0
wincertstore              0.2              py37haa95532_2
xz                        5.2.5                h8cc25b3_1
yaml                      0.2.5                he774522_0
zipp                      3.8.0            py37haa95532_0
zlib                      1.2.12               h8cc25b3_2
zstd                      1.5.2                h19a0ad4_0

**Comment by Emerald01** [comment]
Do you have CUDA driver and compiler installed?

**Comment by DanielWit** [comment]
Yes mate, I am running RTX 3090 with CUDA 11.7 toolkit. All environment variables are sorted, no issues with running models on tensorflow/pytorch

**Comment by Emerald01** [comment]
I suggest you check the file accessibility.
WarpDrive is having some dynamic bin file build, and to start with, it will create a bin folder, and as you saw, on your environment, it cannot open it.

https://github.com/salesforce/warp-drive/blob/7fd245483965f74a0caea0b37d7a98e094dc1274/warp_drive/managers/function_manager.py#L253

**Comment by DanielWit** [comment]
solved after installing the preview version of PyTorch, after I had to uninstall NumPy and install again because apparently NumPy does not support float32 dtype lol what a nightmare 

now got this 

~\miniconda3\envs\warp\lib\site-packages\warp_drive\env_wrapper.py in __init__(self, env_obj, env_name, env_config, num_envs, blocks_per_env, use_cuda, testing_mode, testing_bin_filename, env_registrar, event_messenger, process_id)
     98         self.env.observation_space = recursive_obs_dict_to_spaces_dict(obs)
     99         # Ensure the observation and action spaces share the same keys
--> 100         assert set(self.env.observation_space.keys()) == set(
    101             self.env.action_space.keys()
    102         )

AttributeError: 'Dict' object has no attribute 'keys'

**Comment by DanielWit** [comment]
and that first problem with bin file was related to gym==0.25

**Comment by Emerald01** [comment]
numpy supports float32 from the first version, I think you setup have some conflicts

**Comment by DanielWit** [comment]
I assume you can run this, could you provide a list of dependencies in your env with the versions you use, please?

**Comment by Emerald01** [comment]
There is no magic, 
for example, I suggest you try at Colab first where we just install minimal packages, and in warpdrive itself, it basically installs what the `requirement.txt` is asking for.

https://colab.research.google.com/github/salesforce/warp-drive/blob/master/tutorials/simple-end-to-end-example.ipynb

And we usually used some Docker environment, for our A-100 machine, this is the docker image we used
```
FROM nvcr.io/nvidia/pytorch:21.08-py3
LABEL description="warpdrive-env"

WORKDIR /home/tian-lan/
RUN chmod a+rwx /home/tian-lan/

RUN pip install pycuda==2021.1
```
And inside container, if I have codebase in the local, I just call `pip install -e .`, otherwise I `pip install rl-warp-drive`

**Comment by DanielWit** [comment]
I set up docker, so no connection to conda env's, installed through dockerfile + parameters you stated above, then pip install pycuda and pip install -e . and trying to run run_unittests.py surprise surprise environment can't see NumPy. Installed numpy manually, with same effect wtf (working on pycharm professional). 

anyway thanks for your time I will start all over again tomorrow
