### ISSUE TITLE
PyTorch Lightning Trainer

### ISSUE THREAD

**Issue by tchaton** [salesforce/warp-drive#6]
Hey there,

First of all, thanks for this library, it looks great.

While reading throught the codebase, it seems there is lot of boilerplate.
Might want to consider PyTorch Lightning : https://github.com/PyTorchLightning.

Best,
T.C

**Comment by Emerald01** [comment]
The current main focus of WarpDrive is to provide an end-to-end-at-GPU CUDA boosted multiagent RL environment simulator(step and reset functions) with Python interface. 
Thank you for the feedback about using Pytorch Lightning as the training pipeline. Actually the data such as observation and rewards managed by WarpDrive is designed to be directly accessible by Pytorch as torch.Tensor. So a lot of training pipelines can be adopted once WarpDrive provides the RL environment simulator.

**Comment by Emerald01** [comment]
Sure, let me ask. Thank you.

**Comment by StephanZheng** [comment]
@tchaton interesting, could you share an example of another Lightning example that's representative of what you have in mind?

**Comment by tchaton** [comment]
Hey @StephanZheng @Emerald01,

Here are all our RL examples: https://github.com/PyTorchLightning/lightning-bolts/tree/master/pl_bolts/models/rl

Also, we are building tutorials for the Lightning which are added to the documentation : https://pytorch-lightning.readthedocs.io/en/latest/

I would like to get very clean RL tutorial and believe an example with your library would be great.

Best,
T.C

**Comment by StephanZheng** [comment]
Hi Thomas,

That sounds great. Happy to see if we can help with this. We're quite busy
for the next few weeks b/c of conferences etc. We don't have experience
with Pytorch Lightning, so this would probably take some work from both
sides. How about we schedule a call to discuss this after 10/8?

Stephan Zheng
Lead Research Scientist, Salesforce Research
www.stephanzheng.com

**Comment by sunil-s** [comment]
@tchaton loved the collaboration with the team @ pytorch lightning. Thanks! The PL example went online just yesterday :)
