### ISSUE TITLE
Deprecated PyTorch Lightning Hooks was removed

### ISSUE THREAD

**Issue by moriyan0116** [salesforce/warp-drive#62]
Thanks for great library.

`on_batch_start` and `on_batch_end` was removed on lightning v1.8. 
Please use `on_train_batch_start` and `on_train_batch_end`.

https://github.com/salesforce/warp-drive/blob/3af765fdbccd8917f17c8e68b4e8526973bd5654/warp_drive/training/pytorch_lightning.py#L1011

**Comment by Emerald01** [comment]
Updated accordingly, thank you
