### ISSUE TITLE
Confusion of step function

### ISSUE THREAD

**Issue by fmxFranky** [salesforce/warp-drive#68]
Hi, is the `step()` funtion in `warp_drive` individual for each thread agent? In Figure 1 displayed in the paper, it seemes like that each thread agent in the block maintains a individual `step` function leading the transition function of the system can be paralized. However, in many marl scenarios, the transition of the system must need all agents' actions and then forward the `step` function. Is this a limitation for the repo?

**Comment by Emerald01** [comment]
Not really. In parallel computing, if each agent runs independently, i.e., step() on their own actions, it is a perfect parallel situation. On the other hand, they could be synchronized so merge to one point, for example, in your example, if the transition needs all agents' actions, then you can sync up until all actions are updated.
This is not a limitation for the repo, or parallel computing in general, you may search `synchronize` in the backend CUDA or Numba codes in the repo to understand.

**Comment by fmxFranky** [comment]
Thank you for your reply. In Figure 1 displayed in the paper, each thread agent in the block forward its own step function and then it obtains the next state and reward. According to your reply, i think that the ficture may bring some confusions to the readers and mislead readers since when one agent's step function need others messages (e.g. observation, actions, even global state in the system), the shown figure may make readers think the step scheme have the drawbacks in the mentioned situiation.
And i still don't have a clear understanding about the step function, can you tell me that in warp_drive's parallel computing scheme, can it  implement the joint transition function $T(s, a_1, a_2, \dots, a_n)$ or $T(o_1, o_2, \dots, o_n, a_1, a_2, \dots, a_n)$ in async way?
Thanks a lot~

**Comment by Emerald01** [comment]
example environments may not have the direct answer to this, but this is pretty much the equivalence like here 
https://github.com/salesforce/warp-drive/blob/master/example_envs/tag_gridworld/tag_gridworld_step_pycuda.cu#L84
You sync all the agents actions and the observation requires all the actions being placed.

**Comment by fmxFranky** [comment]
Thanks a lot. Now i know that one can use `synchronize ` in cuda to sync all agents' information and then forward the joint transition function in the system.
