### ISSUE TITLE
AssertionError: the customized environment is expected to be a valid PYTHONPATH

### ISSUE THREAD

**Issue by Finebouche** [salesforce/warp-drive#70]
Hi again,

I am trying to register a custom environment to warp_drive using : 

```
from warp_drive.utils.env_registrar import EnvironmentRegistrar
from stage import Environment

env_registrar = EnvironmentRegistrar()
env_registrar.add_cuda_env_src_path(Environment.name, os.path.abspath("stage.py"), env_backend="numba")

```
However I get the following error : `AssertionError: the customized environment is expected to be a valid PYTHONPATH`

As the documentation for [env_registrar](https://github.com/salesforce/warp-drive/blob/ca6640d23a4e1c35cc40fe7fe48ec3ea78facffb/warp_drive/utils/env_registrar.py#L88) specifies : :param cuda_env_src_path: ABSOLUTE path to the customized environment source code in CUDA,  `os.path.abspath("file_name")` is supposed to get me this absolute path but due to this line of code 

this Error is due to those lines of code in [env_registrar](https://github.com/salesforce/warp-drive/blob/ca6640d23a4e1c35cc40fe7fe48ec3ea78facffb/warp_drive/utils/env_registrar.py#L88)
```
        elif env_backend == "numba":
            assert (
                "/" not in cuda_env_src_path
            ), "the customized environment is expected to be a valid PYTHONPATH"
```

But isn't that contradictory with the doc asking to provide an absolute path ?

**Comment by Emerald01** [comment]
According to the assertion: `assert (
                "/" not in cuda_env_src_path
            ), "the customized environment is expected to be a valid PYTHONPATH"`

the path does not expect "/" to show up but instead ".", because we will load it as a library. 
It is a little inconvenient though, we will improve this point.

**Comment by Finebouche** [comment]
Thank you ! That did the trick :+1:

**Comment by RongjianLiang** [comment]
I am currently having an issue with this one…I replace all the “/“ in the full path to “.”, but it still does not work…need help

**Comment by Emerald01** [comment]
You need to make sure if you can import your environment successfully, WarpDrive just wraps up the Python import
