### ISSUE TITLE
Confusion about environment reset on device and save_and_apply_at_reset

### ISSUE THREAD

**Issue by RongjianLiang** [salesforce/warp-drive#85]
Hi! I would like to ask about resetting the environment that is running on GPU. From what I have read, if GPU backend is used, the environment would only be reset once (via the `reset()` function we define for our environment), and subsequently all data is pushed onto the device, and the `reset()` function would not be called anymore, as `warp_drive` would use those data that is `save_and_apply_at_reset` to automatically innitalize the environement.

If my understanding is right, then how should we deal with those environement attributes that are not `save_and_apply_at_reset`, but need to be re-calculated or generated at every reset? For example, I need to randomly generate some environment attirbutes (like a 2D Numpy arrays representing random city terrains) at every reset, and since this generation is called in `reset()` of my customized environment, it seems that I have to stick to this throughout the entire training process. 

Thanks alot in advance!

**Comment by RongjianLiang** [comment]
For example, let's say I have my environment defined in the following way (this is just a skeleton).Note that I mostly follow the strucutre of the example environment you provide (`tag_continuous`). Please see my comments for `get_data_dict` and `get_tensor_dict`, as well as `reset` for my confusion...thanks in advance! 
```
"""keys for global state dictionary"""
_LOC_X = ...
_LOC_Y = ...
_LOC_Z = ...

"""some environment attributes that have diferent shape than above"""
# might need to change set_global_state() to cater for them
_R_LOC_X = "recording loc_x"            # record agent x locations between step at given sub-step frequency 
_R_LOC_Y = "recording loc_y"            # similar
_R_LOC_Z = "recording loc_z"

# other trivial keys are left out

class DroneReachContinuous(CUDAEnvironmentContext):
    def init(self, ...):
        # init agent ids here  
        # init simulation parameter variables, set them to None first
        # init reward function parameter variables
        # init other variables 
     
    def set_global_state():
        # init value NumPy arrays for new keys 
        # may need to have special array shape for special keys
        
        # init NumPy array values for keys 
        # verify input value arrays have correct shape 
        # again, need to consider speical keys and their values have special shapes

    def generate_obsevation():
        """CPU version"""
        # call other helper functions to generate observation
        return obsevation

    def generate_info():
        """CPU version"""
        # call other helper functions to generate info 
        return observation
    
    def compute_rewards():
        """CPU version"""
      # call other helper functions to compute rewards
      return rewards
    
    def get_data_dict()
        """push data to the datafeed object""" 
        # add the global state dict key-values into datafeed
            # set the save_and_apply_at_reset to True for all of global-state values at t=0(?)

        # add environment attributes to datafeed 
            # for environemnt parameters, like num_agents,  set save_and_apply_at_reset to True
            # for simulation parameters, like simulation_terrains_for_each_episode
            # set save_and_apply_at_reset to False(?)
            # since it is expected to be dfifferent for every new episode... 

    def get_data_tensor_dict():
        """just return an empty datafeed object?"""
        # should return datafeed object with data that could be accessible to PyTorch during training or modified during training
        # like agents location? But they are pushed already in get_data_dict() methods...

    def rest():
        """Env reset"""
        # calculate and set up simulation variables and parameters here 
        # this seems to be only called once for GPU version of the env
        # then how to re-calculated and set-up different values for simulation variables parameters for new episodes?
        # example like:
        self.simulation_terrains = generate_random_simulation_terrains(self.terrains_size, self.terrains_difficulty)

**Comment by Emerald01** [comment]
There are host reset and device reset
1. For the host reset, it only happens once when it deals with vectorization of initial state arrays and push the data to the device: https://github.com/salesforce/warp-drive/blob/master/warp_drive/env_wrapper.py#L264
2. For the device reset, it is a little bit complicated, but you can refer to its manager class
- `reset_when_done()`: WarpDrive will monitor all running environments, and reset those done environments independently, and you are right, we have `save_and_apply_at_reset` flag for the data, so those arrays will be registered for this reset step, what it does is copy the initial data back
the python classes could be referred here:
https://github.com/salesforce/warp-drive/blob/master/warp_drive/managers/function_manager.py#L235
and its backend core could be found here: https://github.com/salesforce/warp-drive/blob/master/warp_drive/cuda_includes/core/reset.cu
3. You are right, this is so far most of the implementation, but we do not have a random reset to re-generate some environment attributes, but we have the placeholders here: https://github.com/salesforce/warp-drive/blob/master/warp_drive/managers/function_manager.py#L232
and its CUDA gateway here: https://github.com/salesforce/warp-drive/blob/master/warp_drive/managers/pycuda_managers/pycuda_function_manager.py#L641
Right now, you just need to implement your custom reset function either in CUDA C or Numba: https://github.com/salesforce/warp-drive/blob/master/warp_drive/managers/pycuda_managers/pycuda_function_manager.py#L636

If you have interest and have a generic enough reset function to regenerate your random start state, you are welcome to contribute and I can help along the way too.

**Comment by RongjianLiang** [comment]
Thanks for the detailed reply and your kind offer to help! 

Actually, I have most of my CPU version of the environment finished, so I already have the function similar to `generate_random_simulation_terrains(self.terrains_size, self.terrains_difficulty` defined, and I am ready to share it with you in the following. 

Currently it is defined in a utility script outside of the main environment script and gets imported into the main script, which is fine for the CPU version of environment. And I think it is necessary to move the relevant utilies function (like this one below)into the Numba step script as addtional helper functions.

After the envrionment getting the returned NumPy array,  it then uses the array to compute some addtional information and store them as Python dictionaries inside environment attributes. They would be read during the environment step. 
These dictionariies are expected to be re-calculated as new episode resets and calls the following helper functon to generate new "city". 

I am thinking of a work-around: since it is a NumPy array with known and fixed sizes (the input parameters would not change throughout the entire training), for Numba-version, I can just initalize it as `np.zeros((env_size, env_size))`and push it to device. In the device step function, for `time_step==1`, I would update this array by calling the genrate function. But the other dicionaries would have to be computed during every steps, as it is unknown to me how to update Python dictionaries in-place. Although the city NumPy array is small in size (about (22, 22)), the computation of dictionaries could be a significant overhead. 

I have created my own repository for this environment (currently only with CPU version, still writing Numba backend, hope to finsh it in the next few hours). The link is here: https://github.com/RongjianLiang/DroneReachContinuous for your reference. 
Anyway, the `generate_random_simulation_terrains` function and its only helper are attached below. 
```
import numpy as np

float_dtype = np.float32
int_dtype = np.int32

SEC_NUM = 2
MIN_MEAN_HEIGHT_PERCENTAGE = 0.3
MAX_MEAN_HEIGHT_PERCENTAGE = 0.7
NUM_INTERVAL = 10
HEIGHT_VARIANCE = 5.5

coords2blocks = np.array(
    [-0.5, -0.5, -0.5], dtype=float_dtype
)


def p_dict_to_block_list(data):
    """
    Given a dictionary whose values are numpy array representing points coordinates,
    calculate blocks number that holds these points. Assume that block index starts
    from 0 and of size 1x1x1.
    :param data: a dictionary whose values are numpy array for points coordinates.
    :return: a numpy array of blocks number of type np.int32.
    """
    assert isinstance(data, dict)
    coords_source = data.values()
    loc_list = np.unique(
        [
            int_dtype(coords - coords % 1) for coords in coords_source
        ],
        axis=0
    )
    return loc_list


def generate_city_padded(
        env_size: int,
        max_buildings_height: int,
        difficulty_level: int,
        d_centroid: np.ndarray,
        d_dict: dict):
    """
    Generate a city with buildings of various height.
    This is a highly simplified and optimized version of the original generate function.
    The city is additionally padded with empty space to allow for periodic borders and spawning, without
    altering the generated terrain too much.
    Only the drone spawned position will directly alter the city terrains.
    And since goals are spawned at the padded region, which is beyond the sensing range of drones at most cases,
    line-of-sight is no longer needed.
    Args:
        env_size: size of the environment.
            Provided by the caller inside environment class.
        max_buildings_height: maximum building height of the environment.
            Provided by the caller inside environment class.
        difficulty_level: An integer value for calculating number of buildings.
            Provided by the caller inside environment class.
        d_centroid: A NumPy array of shape (3, ) indicating the coordinates of drone centroids.
            For example, np.array([10.5, 10.5, 10], dtype=np.float32)
            Provided by the caller inside environment class.
        d_dict: A dictionary whose keys are agent ids of drones, values being their starting
            coordinates represented by NumPy arrays.
            For example, {1: np.array([1,2,3]), 2: np.array([4,5,6])}
            Provided by the caller inside environment class.
    Returns:
        A NumPy array of shape (env_size, env_size).

    """
    # validity check 
    assert isinstance(env_size, int)
    env_size = int_dtype(env_size)
    assert isinstance(max_buildings_height, int)
    max_buildings_height = int_dtype(max_buildings_height)
    assert isinstance(difficulty_level, int)
    assert isinstance(d_dict, dict)
    

    sec_size = env_size - 2         # the border is padded
    d_blk = p_dict_to_block_list(d_dict)
    h_m_list = np.linspace(MIN_MEAN_HEIGHT_PERCENTAGE, MAX_MEAN_HEIGHT_PERCENTAGE, NUM_INTERVAL)
    h_m = np.random.choice(h_m_list)
    h_s = HEIGHT_VARIANCE
    num_per_sec = float_dtype(difficulty_level / 10)
    b_num = int_dtype(num_per_sec * sec_size * sec_size)
    h_min = np.zeros(b_num, dtype=int_dtype)
    h_max = np.full(b_num, max_buildings_height, dtype=int_dtype)

    d_centroid_blk = int_dtype(d_centroid + coords2blocks)

    # set the buildings
    buf = np.zeros((sec_size, sec_size))
    building_indices = np.random.choice(sec_size * sec_size, b_num, replace=False)
    buildings_height = np.clip(np.random.normal(h_m, h_s, b_num), h_min, h_max)
    buf.flat[building_indices] = buildings_height

    # padding
    pad1 = np.zeros((1, env_size))
    pad2 = np.zeros((env_size - 2, 1))
    buf = np.concatenate((pad2, buf, pad2), axis=1)
    buf = np.vstack((pad1, buf, pad1))

    # make sure the drones do not interfere with the buildings
    envelope = np.full((env_size, env_size), max_buildings_height, dtype=int_dtype)
    for (x, y, z) in d_blk:
        if envelope[x, y] > z:  # only update the entry if there is a smaller one.
            envelope[x, y] = z - 1

    city = np.where(buf < envelope, buf, envelope)

    return city
```

**Comment by Emerald01** [comment]
Hi @RongjianLiang 
this seems an interesting project, and we are looking for a good motivation to generate a random environment reset function. I do not fully understand yours, sorry I have no time to consume your specific environment in great detail. 

- So first let me tell you what the special character of reset function in WarpDrive:

Since WarpDrive manages, say 100 concurrent environments, each environment may reach the terminal at different time (and hence reset at different time), WarpDrive will manage to only reset "done" environments while not bothering other environments. This is an important concept, this means that you may not use one single host function to write a reset function, then reset a particular environment replica and push back to device, this is too slow not because the data push (I assume the data size is small) but because this becomes a single point to control all concurrency.

- Secondly, what we can do
1. if your environment reset is just a random one without dependency on your previous state, then you can create a pool of different starting configurations, and in the reset, you can just randomly pick up this or that from the pool and this could be a good random reset
2. otherwise, the reset of each of your environment replica is also a function of some previous updated state, for example, like`random_reset(*list_of_states_from_previous_episode)`, then you have no choice but reset it at the runtime

Please let me know yours, I may create a skeleton for you so you can add in your details. If you are using Numba environment version, I do not think it is pretty difficult to execute either 1 or 2

**Comment by RongjianLiang** [comment]
Hi @Emerald01 
Thanks for your prompt reply and suggestion! 
For my case, the first one (creating a pool at initialization and push to device for random choice) shuold fit my requirements good enough.
 
In this approach actually, I might not actually want to let the numba step function uses the raw NumPy arrays which are just easy representations of "city", but uses the post-processed ones (with more information, similar to the Python dictionaries I mentioned earlier). Anyway, it would be a pool of NumPy ararays, just that their individual size might be bigger than (22, 22). 

And thanks for sharing the details of resetting concurrent environment! Indeed, having a single functions controlling all the environment replica implies some overhead (I guess it is because of some operation orderings are required to prevent data races, which limit the potential for concurrency).

For implementing the first solution, I think some minor modificaton to the step function and the one-time reset/init in the environment are required. It would be of great help if you could provide the skeleton for me to work on. Please let me know your arrangments on this asap. As I am full-time on developing this environment, I am always on standby.

**Comment by Emerald01** [comment]
So what’s your backend choice, CUDA C or Numba? Depending on your choice, I will populate a reset template for you to use. BTW, have you done with your backup environment and tested it? This codebase is mostly for GPU and would not run at host or Python alone

**Comment by RongjianLiang** [comment]
The backend would be Numba. I understand that the environment requires both host and device functions to be defined. The CPU backend version has been unittested (yet to perform integrated testing).

**Comment by RongjianLiang** [comment]
Hi! How is the thing going on? I am still looking forward to using the template to further build the project!

**Comment by Emerald01** [comment]
Hello,

Sorry we do not have that much bandwidth to quickly update the code as you requested. But over the past few days I am mostly done with your ask. Now you should be able to proceed.

So the main idea is that we will have a `add_pool_for_reset()` method in `DataFeed`
https://github.com/salesforce/warp-drive/blob/random-reset/warp_drive/utils/data_feed.py#L89
Inside `DataManager` and `FunctionManager`, it will handle all logic issues and sanity checks, for example, we will make sure data types and shapes are the same between the pool and its target data:
https://github.com/salesforce/warp-drive/blob/random-reset/warp_drive/managers/numba_managers/numba_function_manager.py#L399

we will also make sure now the target data has not set up flag "save_copy_and_apply_at_reset", otherwise there are two conflict ways to reset one single data:
https://github.com/salesforce/warp-drive/blob/random-reset/warp_drive/managers/data_manager.py#L237
https://github.com/salesforce/warp-drive/blob/random-reset/warp_drive/managers/data_manager.py#L287

Then under the hood, `NumbaEnvResetter` will do the job to randomly pick up the candidate in the reset pool and reset accordingly. Just keep in mind that, for the first time reset, it will still use the same data for all env replicas.

An example for user interface to use this new functionality is like this, please note that we have this functionality `get_reset_pool_dictionary()` reserved for this pool reset job for any environment if you want `EnvWrapper` to understand.

**Comment by RongjianLiang** [comment]
Many thanks for your detailed answer and the new functionalities! I would pull the latest repository and give it a try!
