### ISSUE TITLE
support gymnasium >= 0.26?

### ISSUE THREAD

**Issue by cboettig** [salesforce/warp-drive#86]
Thanks for sharing this impressive resource!  I see the config currently restricts installation to before breaking changes were introduced into the `gymnasium` package in its version 0.26 release.  Are there plans to migrate to supporting the latest version of the gym/gymnasium package?  You are probably already familiar with the offical [migration guide](https://gymnasium.farama.org/content/migration-guide/)

**Comment by Emerald01** [comment]
In the next release 2.5.0, we will remove this restriction. Our codebase is very weakly dependent on gym module. We used it to define our environment attributes and random seeding in our outer Python wrapper. Internally our code has no dependence on gym.

**Comment by cboettig** [comment]
Thanks @Emerald01 ! yup, noted that the gym module isn't really used here anyway; its just nice not to have to maintain a separate virtualenv for my warp-drive examples when doing any benchmark them against gym-based RL just avoid the conflict :-).  sorry for the trouble and have really been enjoying getting my teeth into warp-drive so far!
