### ISSUE TITLE
The hyperlink for the full reference documentation isn't working.

### ISSUE THREAD

**Issue by RadwaSK** [salesforce/warp-drive#9]
In this sentence in the README file: "You can find full reference documentation here."
The hyperlink in "here" isn't working.

**Comment by Emerald01** [comment]
Thank you. Just fixed the link.
We are still actively developmenting the code by adding more interesting and useful multiagent environments and improving the user experience. You are more than welcome to try it and bring up your suggestions and concerns. Keep watching!
